name: Deploy HUB API to VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/HUB-api
            git stash                          # Protege mudanças locais
            git pull origin main --rebase      # Puxa o código novo
            git stash pop || true              # Tenta devolver as mudanças (ignora erro se não houver nada)
            rm -rf node_modules
            npm install
            npm audit fix
            docker compose down
            docker compose up -d --build